name: hotel_finder
description: A beautiful hotel search application with Google Sign-In
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  intl: ^0.18.1
  # Authentication
  google_sign_in: ^6.1.5
  device_info_plus: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.0


  # HTTP Request
  http: ^1.1.0

  # UI Componentss
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/google.png